server:
  port: 8186
spring:
  application:
    name: sim-basic
  session:
    store-type: redis
  cache:
    type: redis
    database: 1
  redis:
    host: localhost
    port: 6379
    timeout: 36000
    database: 0
    password:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/flowable?characterEncoding=utf8&useSSL=false
    username: flowable
    password: flowable
    driver-class-name: com.mysql.jdbc.Driver
management:
  security:
     enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:8081/eureka/
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
feign:
  httpclient:
    enabled: true
